
    - name: configure mail settings
      blockinfile:
        path: /etc/msmtprc
        block: |
          defaults
          port {{ mail_port }}
          tls on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          account {{ mail_from }}
          host {{ mail_relay }}
          set_from_header on
          from {{ mail_from }}
          account default: {{ mail_from }}
          aliases /etc/aliases
          logfile /var/log/msmtp
        create: true

    - name: chmod mail config file
      file:
        path: /etc/msmtprc
        group: msmtp
        mode: '640'

    - name: configure mail settings pt. 2
      lineinfile:
        dest: /etc/aliases
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: true
      loop:
        - { regexp: '^root:', line: 'root: {{ mail_to }}' }
        - { regexp: '^default:', line: 'default: {{ mail_to }}' }

    - name: configure mail settings pt. 3
      lineinfile:
        path: /etc/mail.rc
        regexp: '^set sendmail'
        line: 'set sendmail="/usr/bin/msmtp -t"'
        create: yes

    - name: send a testmail
      shell: echo "Testmail" | mail -s "[{{ ansible_hostname }}] Testmail" {{ mail_to }}
      when:
        - send_testmail | bool

